' 待ち受け中からルアー投入、ロックまでのユースケース
@startuml

actor User
actor Operator

User --> (キャッチボックス) : << ルアー投入 >>
User <-- (キャッチボックス) : << 景品獲得 または失敗 >>
(CPUボード) <.. (キャッチボックス) : << センサ検知通知 >>
(CPUボード) ..> (キャッチボックス) : << 景品獲得通知 >>
(CPUボード) ..> (景品獲得表示器) : << 景品獲得通知 >>
Operator <-- (景品獲得表示器) : << 景品獲得検知 >>
Operator --> (キャッチボックス) : << 景品セット >>
@enduml

' 待ち受け中からルアー投入、ロックまでのユースケース
@startuml

actor User
actor Operator

User --> (キャッチボックス) : << ルアー投入 >>
(キャッチボックス) --> (ロックセンサ) : << センサ検知 >>
(CPUボード) <.. (ロックセンサ) : << センサ検知通知 >>
(CPUボード) ..> (ロックアクチュエータ) : << ロック要求通知 >>

(CPUボード) ..> (モーションアクチュエータ) : << モーション動作信号 >>
(CPUボード) ..> (景品獲得表示器) : << 停止信号 >>
@enduml

' ルアーロックからユーザーのルアー取り出しまでのユースケース
@startuml

actor User
actor Operator

User <-- (キャッチボックス) : << ルアー取り出し >>
Operator <-- (景品獲得表示器) : << 景品獲得検知 >>
Operator --> (キャッチボックス) : << 景品セット >>
(キャッチボックス) --> (ロックセンサ) : << ロック解除センサ検知 >>
(CPUボード) <.. (ルアーセンサ) : << ルアー引き上げ検知通知 >>
(CPUボード) <.. (ロックセンサ) : << ロック解除検知通知 >>
(CPUボード) ..> (ロックアクチュエータ) : << ロック解除要求通知 >>

(CPUボード) ..> (モーションアクチュエータ) : << モーション停止信号 >>
(CPUボード) ..> (景品獲得表示器) : << 表示信号 >>
@enduml
